# frozen_string_literal: true

require_relative "../base_generator"

module Boilermaker
  module Generators
    class PaymentsGenerator < BaseGenerator
      source_root File.expand_path("templates", __dir__)

      desc "Generates a complete subscription billing system using Pay gem with Stripe"

      def prompt_scope
        @scope = prompt_for_scope("subscription")
        say "Using #{@scope} scope for payments", :green
      end

      def add_pay_gem
        add_gem("pay", "~> 7.0")
        add_gem("stripe", "~> 12.0")
        bundle_install
      end

      def install_pay
        say "Installing Pay gem...", :yellow
        run "bin/rails pay:install:migrations"
      end

      def create_pay_initializer
        template "initializers/pay.rb.tt",
                 "config/initializers/pay.rb"
      end

      def add_pay_customer_to_model
        model_file = @scope == :account ? "app/models/account.rb" : "app/models/user.rb"
        model_content = File.read(Rails.root.join(model_file))

        unless model_content.include?("pay_customer")
          # Find the class definition line
          class_line = model_content.match(/^class \w+ < ApplicationRecord\n/)
          if class_line
            insert_point = class_line.end(0)
            new_content = model_content.insert(insert_point, "  pay_customer\n")
            File.write(Rails.root.join(model_file), new_content)
            say "Added pay_customer to #{@scope.to_s.classify} model", :green
          end
        end
      end

      def create_controller
        template "controllers/payments_controller.rb.tt",
                 "app/controllers/payments_controller.rb"
      end

      def create_views
        template "views/payments/pricing.rb.tt",
                 "app/views/payments/pricing.rb"
        template "views/settings/billing.rb.tt",
                 "app/views/settings/billing.rb"
      end

      def create_components
        template "components/pricing_card.rb.tt",
                 "app/components/pricing_card.rb"
        template "components/subscription_status.rb.tt",
                 "app/components/subscription_status.rb"
      end

      def create_feature_concern
        create_feature_concern("payments")
      end

      def create_routes
        route_content = <<~RUBY
          # frozen_string_literal: true

          # Payment routes
          # Generated by: bin/rails generate boilermaker:payments

          Rails.application.routes.draw do
            # Pricing page
            get "pricing", to: "payments#pricing"

            # Checkout and portal
            scope :payments do
              post "checkout/:plan", to: "payments#checkout", as: :checkout
              get  "success",        to: "payments#success",  as: :payment_success
              get  "cancel",         to: "payments#cancel",   as: :payment_cancel
              post "portal",         to: "payments#portal",   as: :billing_portal
            end

            # Settings sub-page for billing
            namespace :settings do
              resource :billing, only: [:show]
            end
          end
        RUBY

        create_route_file("payments", route_content)
      end

      def update_configuration
        update_config(
          payments: true,
          payments_scope: @scope.to_s,
          payments_provider: "stripe"
        )
      end

      def add_seeds
        seed_content = <<~RUBY
          # Payment seeds (development only)
          if Rails.env.development?
            puts "Payments feature installed."
            puts "Create your plans in Stripe Dashboard, then add them to config/initializers/pay.rb"
            puts "Example plans: starter ($9/mo), professional ($29/mo), enterprise ($99/mo)"
          end
        RUBY

        append_seeds(seed_content)
      end

      def create_tests
        return if options[:skip_tests]

        template "tests/payments_controller_test.rb.tt",
                 "test/controllers/payments_controller_test.rb"
      end

      def print_instructions
        print_next_steps([
          "Run migrations: bin/rails db:migrate",
          "Configure Stripe keys in credentials:",
          "  bin/rails credentials:edit",
          "  Add: stripe: { private_key: sk_xxx, public_key: pk_xxx, webhook_secret: whsec_xxx }",
          "Create plans in Stripe Dashboard",
          "Set webhook URL in Stripe: https://yourapp.com/pay/webhooks/stripe",
          "Update config/initializers/pay.rb with your plan details"
        ])
      end

      private

      def scope_model_class
        @scope == :account ? "Account" : "User"
      end

      def scope_current
        @scope == :account ? "Current.account" : "Current.user"
      end
    end
  end
end
