# frozen_string_literal: true

require_relative "../base_generator"

module Boilermaker
  module Generators
    class ImpersonationGenerator < BaseGenerator
      source_root File.expand_path("templates", __dir__)

      desc "Generates a complete impersonation system for admin users"

      def create_migration
        timestamp = Time.now.utc.strftime("%Y%m%d%H%M%S")
        template "migrations/add_impersonator_to_sessions.rb.tt",
                 "db/migrate/#{timestamp}_add_impersonator_to_sessions.rb"
      end

      def create_controller
        template "controllers/masquerades_controller.rb.tt",
                 "app/controllers/masquerades_controller.rb"
      end

      def create_banner_component
        template "components/impersonation_banner.rb.tt",
                 "app/components/impersonation_banner.rb"
      end

      def create_impersonation_feature_concern
        create_feature_concern("impersonation")
      end

      def create_routes
        route_content = <<~RUBY
          # frozen_string_literal: true

          # Impersonation routes
          # Generated by: bin/rails generate boilermaker:impersonation

          Rails.application.routes.draw do
            # Impersonation - admin can masquerade as another user
            post   "users/:user_id/masquerade", to: "masquerades#create", as: :user_masquerade
            delete "masquerade",                to: "masquerades#destroy", as: :stop_masquerade
          end
        RUBY

        create_route_file("impersonation", route_content)
      end

      def update_configuration
        update_config(impersonation: true)
      end

      def create_tests
        return if options[:skip_tests]

        template "tests/masquerades_controller_test.rb.tt",
                 "test/controllers/masquerades_controller_test.rb"
      end

      def remove_old_masquerade_route
        routes_file = Rails.root.join("config", "routes.rb")
        content = File.read(routes_file)

        # Remove the old inline masquerade route if present
        old_route = /^\s*#\s*Masquerading\s*\n\s*post\s+"users\/:user_id\/masquerade".*\n/
        if content.match?(old_route)
          new_content = content.gsub(old_route, "")
          File.write(routes_file, new_content)
          say "Removed old masquerade route from routes.rb (now in config/routes/impersonation.rb)", :green
        end
      end

      def update_session_model
        session_file = Rails.root.join("app", "models", "session.rb")
        session_content = File.read(session_file)

        # Add belongs_to :impersonator if not present
        unless session_content.include?("belongs_to :impersonator")
          insert_after = "belongs_to :account, optional: true\n"
          addition = "  belongs_to :impersonator, class_name: \"User\", optional: true\n"

          if session_content.include?(insert_after)
            new_content = session_content.gsub(insert_after, "#{insert_after}#{addition}")
            File.write(session_file, new_content)
            say "Added impersonator association to Session model", :green
          end
        end
      end

      def update_layout_for_banner
        layout_file = Rails.root.join("app", "views", "layouts", "application.rb")
        layout_content = File.read(layout_file)

        # Add impersonation banner rendering if not present
        unless layout_content.include?("ImpersonationBanner")
          # Find a good place to insert - after the body tag opening
          insert_point = layout_content.index("body(class: body_classes) do")
          if insert_point
            end_of_line = layout_content.index("\n", insert_point)
            if end_of_line
              banner_code = "\n            render Components::ImpersonationBanner.new if Current.session&.impersonator.present?\n"
              new_content = layout_content.insert(end_of_line + 1, banner_code)
              File.write(layout_file, new_content)
              say "Added ImpersonationBanner to application layout", :green
            end
          end
        end
      end

      def print_instructions
        print_next_steps([
          "Run migrations: bin/rails db:migrate",
          "The impersonation feature is now active for app_admin users",
          "Admin users can impersonate from Admin > Users > [user] > Masquerade",
          "A banner will appear when impersonating with an 'Exit' button",
          "Cannot impersonate other admins (for security)"
        ])
      end
    end
  end
end
