# frozen_string_literal: true

require_relative "../base_generator"

module Boilermaker
  module Generators
    class NotificationsGenerator < BaseGenerator
      source_root File.expand_path("templates", __dir__)

      desc "Generates a complete in-app notification system using the Noticed gem"

      def prompt_scope
        @scope = prompt_for_scope("notifications")
        say "Using #{@scope} scope for notifications", :green
      end

      def add_noticed_gem
        add_gem("noticed", "~> 2.0")
        bundle_install
      end

      def install_noticed
        say "Installing Noticed gem...", :yellow
        run "bin/rails noticed:install:migrations"
      end

      def create_notification_concern
        template "models/notifiable.rb.tt",
                 "app/models/concerns/notifiable.rb"
      end

      def update_scope_model
        model_file = @scope == :account ? "app/models/account.rb" : "app/models/user.rb"
        model_content = File.read(Rails.root.join(model_file))

        unless model_content.include?("Notifiable")
          # Find the class definition line
          class_line = model_content.match(/^class \w+ < ApplicationRecord\n/)
          if class_line
            insert_point = class_line.end(0)
            new_content = model_content.insert(insert_point, "  include Notifiable\n")
            File.write(Rails.root.join(model_file), new_content)
            say "Added Notifiable concern to #{@scope.to_s.classify} model", :green
          end
        end
      end

      def create_controller
        template "controllers/notifications_controller.rb.tt",
                 "app/controllers/notifications_controller.rb"
      end

      def create_views
        template "views/notifications/index.rb.tt",
                 "app/views/notifications/index.rb"
      end

      def create_components
        template "components/notification_bell.rb.tt",
                 "app/components/notification_bell.rb"
        template "components/notification_item.rb.tt",
                 "app/components/notification_item.rb"
      end

      def create_example_notifiers
        template "notifiers/welcome_notifier.rb.tt",
                 "app/notifiers/welcome_notifier.rb"
        template "notifiers/application_notifier.rb.tt",
                 "app/notifiers/application_notifier.rb"
      end

      def create_settings_page
        template "views/settings/notifications.rb.tt",
                 "app/views/settings/notifications.rb"
      end

      def create_feature_concern
        create_feature_concern("notifications")
      end

      def create_routes
        route_content = <<~RUBY
          # frozen_string_literal: true

          # Notification routes
          # Generated by: bin/rails generate boilermaker:notifications

          Rails.application.routes.draw do
            resources :notifications, only: [:index, :show] do
              collection do
                post :mark_all_read
              end
              member do
                post :mark_read
              end
            end

            # Settings sub-page for notification preferences
            namespace :settings do
              resource :notifications, only: [:show, :update]
            end
          end
        RUBY

        create_route_file("notifications", route_content)
      end

      def update_configuration
        update_config(
          notifications: true,
          notifications_scope: @scope.to_s
        )
      end

      def add_seeds
        seed_content = <<~RUBY
          # Notification seeds (development only)
          if Rails.env.development?
            puts "Seeding notifications..."
            # Sample notifications will be created when WelcomeNotifier is triggered
            # You can trigger it manually: WelcomeNotifier.with(message: "Hello!").deliver(User.first)
          end
        RUBY

        append_seeds(seed_content)
      end

      def create_tests
        return if options[:skip_tests]

        template "tests/notifications_controller_test.rb.tt",
                 "test/controllers/notifications_controller_test.rb"
      end

      def print_instructions
        print_next_steps([
          "Run migrations: bin/rails db:migrate",
          "Add the notification bell to your navigation (slot in AppHeader or Navigation)",
          "Example: render Components::NotificationBell.new(recipient: Current.user)",
          "Send notifications: WelcomeNotifier.with(message: 'Hello!').deliver(recipient)",
          "Configure notification preferences at /settings/notifications"
        ])
      end

      private

      def scope_model_class
        @scope == :account ? "Account" : "User"
      end

      def scope_current
        @scope == :account ? "Current.account" : "Current.user"
      end
    end
  end
end
