# frozen_string_literal: true

require_relative "../base_generator"

module Boilermaker
  module Generators
    class AuditLogGenerator < BaseGenerator
      source_root File.expand_path("templates", __dir__)

      desc "Generates a complete audit logging system for tracking changes to sensitive models"

      class_option :retention_days, type: :numeric, default: 90,
                                    desc: "Number of days to retain audit logs"

      def create_migration
        timestamp = Time.now.utc.strftime("%Y%m%d%H%M%S")
        template "migrations/create_audit_logs.rb.tt",
                 "db/migrate/#{timestamp}_create_audit_logs.rb"
      end

      def create_model
        template "models/audit_log.rb.tt",
                 "app/models/audit_log.rb"
      end

      def create_auditable_concern
        template "models/auditable.rb.tt",
                 "app/models/concerns/auditable.rb"
      end

      def create_controller
        template "controllers/audit_logs_controller.rb.tt",
                 "app/controllers/admin/audit_logs_controller.rb"
      end

      def create_views
        template "views/audit_logs/index.rb.tt",
                 "app/views/admin/audit_logs/index.rb"
        template "views/audit_logs/show.rb.tt",
                 "app/views/admin/audit_logs/show.rb"
      end

      def create_cleanup_job
        template "jobs/audit_log_cleanup_job.rb.tt",
                 "app/jobs/audit_log_cleanup_job.rb"
      end

      def add_auditable_to_models
        %w[User Account Session].each do |model_name|
          add_auditable_to_model(model_name)
        end
      end

      def create_feature_concern
        create_feature_concern("audit_log")
      end

      def create_routes
        route_content = <<~RUBY
          # frozen_string_literal: true

          # Audit log routes
          # Generated by: bin/rails generate boilermaker:audit_log

          Rails.application.routes.draw do
            namespace :admin do
              resources :audit_logs, only: [:index, :show] do
                collection do
                  get :export
                end
              end
            end
          end
        RUBY

        create_route_file("audit_log", route_content)
      end

      def update_configuration
        update_config(
          audit_log: true,
          audit_log_retention_days: options[:retention_days]
        )
      end

      def configure_recurring_job
        recurring_file = Rails.root.join("config", "recurring.yml")

        if File.exist?(recurring_file)
          content = File.read(recurring_file)
          unless content.include?("audit_log_cleanup")
            append_to_file recurring_file, <<~YAML

              audit_log_cleanup:
                class: AuditLogCleanupJob
                schedule: every day at 3am
                description: "Clean up old audit logs"
            YAML
            say "Added AuditLogCleanupJob to config/recurring.yml", :green
          end
        else
          create_file recurring_file, <<~YAML
            # SolidQueue recurring jobs
            # See: https://github.com/rails/solid_queue

            audit_log_cleanup:
              class: AuditLogCleanupJob
              schedule: every day at 3am
              description: "Clean up old audit logs"
          YAML
          say "Created config/recurring.yml with AuditLogCleanupJob", :green
        end
      end

      def create_tests
        return if options[:skip_tests]

        template "tests/audit_log_test.rb.tt",
                 "test/models/audit_log_test.rb"
        template "tests/audit_logs_controller_test.rb.tt",
                 "test/controllers/admin/audit_logs_controller_test.rb"
      end

      def print_instructions
        print_next_steps([
          "Run migrations: bin/rails db:migrate",
          "User, Account, and Session changes are now automatically logged",
          "Add 'include Auditable' to other models you want to track",
          "View audit logs at /admin/audit_logs (admin only)",
          "Logs are retained for #{options[:retention_days]} days (configurable)",
          "Cleanup job runs daily via SolidQueue recurring jobs"
        ])
      end

      private

      def add_auditable_to_model(model_name)
        model_file = Rails.root.join("app", "models", "#{model_name.underscore}.rb")
        return unless File.exist?(model_file)

        model_content = File.read(model_file)

        unless model_content.include?("Auditable")
          # Find the class definition line
          class_line = model_content.match(/^class \w+ < ApplicationRecord\n/)
          if class_line
            insert_point = class_line.end(0)
            new_content = model_content.insert(insert_point, "  include Auditable\n")
            File.write(model_file, new_content)
            say "Added Auditable concern to #{model_name} model", :green
          end
        end
      end

      def retention_days
        options[:retention_days]
      end
    end
  end
end
