# frozen_string_literal: true

require_relative "../base_generator"

module Boilermaker
  module Generators
    class UploadsGenerator < BaseGenerator
      source_root File.expand_path("templates", __dir__)

      desc "Generates file upload components with ActiveStorage and Stimulus"

      def check_active_storage
        unless File.exist?(Rails.root.join("config", "storage.yml"))
          say "Installing ActiveStorage...", :yellow
          run "bin/rails active_storage:install"
        else
          say "ActiveStorage already installed", :green
        end
      end

      def create_components
        template "components/file_upload.rb.tt",
                 "app/components/file_upload.rb"
        template "components/file_preview.rb.tt",
                 "app/components/file_preview.rb"
        template "components/file_list.rb.tt",
                 "app/components/file_list.rb"
      end

      def create_stimulus_controller
        template "javascript/upload_controller.js.tt",
                 "app/javascript/controllers/upload_controller.js"
      end

      def add_direct_upload_to_importmap
        importmap_file = Rails.root.join("config", "importmap.rb")
        importmap_content = File.read(importmap_file)

        unless importmap_content.include?("@rails/activestorage")
          append_to_file importmap_file, <<~RUBY

            # ActiveStorage direct uploads
            pin "@rails/activestorage", to: "activestorage.esm.js"
          RUBY
          say "Added @rails/activestorage to importmap", :green
        end
      end

      def add_direct_upload_to_application_js
        application_js = Rails.root.join("app", "javascript", "application.js")
        return unless File.exist?(application_js)

        content = File.read(application_js)

        unless content.include?("@rails/activestorage")
          append_to_file application_js, <<~JS

            // ActiveStorage direct uploads
            import * as ActiveStorage from "@rails/activestorage"
            ActiveStorage.start()
          JS
          say "Added ActiveStorage import to application.js", :green
        end
      end

      def create_feature_concern
        create_feature_concern("uploads")
      end

      def create_routes
        route_content = <<~RUBY
          # frozen_string_literal: true

          # Upload routes (optional standalone endpoints)
          # Generated by: bin/rails generate boilermaker:uploads

          Rails.application.routes.draw do
            # Add standalone upload endpoints here if needed
            # Example:
            # resources :documents, only: [:create, :destroy]
          end
        RUBY

        create_route_file("uploads", route_content)
      end

      def update_configuration
        update_config(uploads: true)
      end

      def create_tests
        return if options[:skip_tests]

        template "tests/file_upload_component_test.rb.tt",
                 "test/components/file_upload_component_test.rb"
      end

      def print_instructions
        print_next_steps([
          "Run migrations: bin/rails db:migrate (for ActiveStorage tables)",
          "Add attachments to your models: has_one_attached :avatar",
          "Use components in your views:",
          "  render Components::FileUpload.new(name: 'user[avatar]')",
          "  render Components::FilePreview.new(attachment: @user.avatar)",
          "For production: Configure cloud storage in config/storage.yml"
        ])
      end
    end
  end
end
